---
title: "Discovering motifs in yeast ChIP-seq peaks"
subtitle: "Paris-Diderot, Oct 4, 2018"
author: "Jacques van Helden"
date: '`r Sys.Date()`'
output:
  html_document:
    self_contained: no
    fig_caption: yes
    highlight: zenburn
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    fig_caption: yes
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_depth: 4
  word_document: default
editor_options: 
  chunk_output_type: console
#css: ../../course.css
---

# Introduction


# Requirements


# Resources

| Resource | URL | Descrption |
|-------------|---------------------|----------------------------|
| RSAT | http://rsat.eu/ | Regulatory Sequence Analysis Tools, a Software suite for the analysis of cis-regulatory motifs in nucleic sequences |
| RSAT Fungi | http://fungi.rsat.eu/ | RSAT server dedicated to Fungi |
| RSAT teaching | http://teaching.rsat.eu/ | RSAT for teaching, with organisms from diverse taxa |
| Yeastract | http://www.yeastract.com/ | YEASTRACT (Yeast Search for Transcriptional Regulators And Consensus Tracking) is a curated repository of approximately 163000 regulatory associations between transcription factors (TF) and target genes in Saccharomyces cerevisiae, based on more than 1600 bibliographic references. |
|JASPAR | http://jaspar.genereg.net/ | Database of transcription factor binding motifs in eukaryotes |
| JASPAR core Fungi clustering | http://jaspar.genereg.net/matrix-clusters/fungi/ | clustering of all the fungal TF binding motifs from Jaspar |

# Study case

Dataset provided by Gaëlle Lelandais: sequences (in fasta format) of 122 peaks identified with a ChIP-seq experiment with the yeast Pdr1 transcription factor. 

- [122peaks_bPeaks_allGenome_20140106_140423_v25.fasta.gz](data/122peaks_bPeaks_allGenome_20140106_140423_v25.fasta.gz)

# Tutorial


# Exercises


